# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caramelo < Formula
  desc "Caramelo CLI — manage AI coding skills from your terminal"
  homepage "https://caramelo.dev"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FreVis/caramelo-cli/releases/download/v0.0.1/caramelo_0.0.1_macos_amd64.tar.gz"
      sha256 "36b981d3f7823af70055d85cc596870202da13f51c60e2ff0ccd32903de11f98"

      define_method(:install) do
        bin.install "caramelo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FreVis/caramelo-cli/releases/download/v0.0.1/caramelo_0.0.1_macos_arm64.tar.gz"
      sha256 "5485c668a75930b3039aecff7cb139fdb89793667c92d886d43c1aea23bb3cb0"

      define_method(:install) do
        bin.install "caramelo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreVis/caramelo-cli/releases/download/v0.0.1/caramelo_0.0.1_linux_amd64.tar.gz"
      sha256 "e098a7bc1c56e20abe913ff4be7bf9658e70de8397fc67018acf21a5ba57e3f5"
      define_method(:install) do
        bin.install "caramelo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreVis/caramelo-cli/releases/download/v0.0.1/caramelo_0.0.1_linux_arm64.tar.gz"
      sha256 "6ab95ee194172330547b4f90b7639c3449b31c30730b923733351a82ba654287"
      define_method(:install) do
        bin.install "caramelo"
      end
    end
  end

  test do
    system "#{bin}/caramelo", "version"
  end
end
