# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caramelo < Formula
  desc "Caramelo CLI — manage AI coding skills from your terminal"
  homepage "https://caramelo.dev"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FreVis/homebrew-caramelo/releases/download/v0.0.3/caramelo_0.0.3_macos_amd64.tar.gz"
      sha256 "676314bb52ed1569554294fe42f2d7d90f3a779c3276b92fde424cb7e7a58e80"

      define_method(:install) do
        bin.install "caramelo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FreVis/homebrew-caramelo/releases/download/v0.0.3/caramelo_0.0.3_macos_arm64.tar.gz"
      sha256 "a3687337b06e684304942e6bbf77be7e6c6bcd82aabc6141dc3bf41039d3c754"

      define_method(:install) do
        bin.install "caramelo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreVis/homebrew-caramelo/releases/download/v0.0.3/caramelo_0.0.3_linux_amd64.tar.gz"
      sha256 "4d237aa123bceb3dbf3bf8b97f96ae30b720bce98141fe21fab38f8014cd009b"
      define_method(:install) do
        bin.install "caramelo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreVis/homebrew-caramelo/releases/download/v0.0.3/caramelo_0.0.3_linux_arm64.tar.gz"
      sha256 "57b00c298dbe8d0d5964d2cd733582ba3f3ab90a03299ab7a4cae24982754667"
      define_method(:install) do
        bin.install "caramelo"
      end
    end
  end

  test do
    system "#{bin}/caramelo", "version"
  end
end
